include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.swagger.dart'
    - '**/api/proto/**/*.dart'
  errors:
      invalid_annotation_target: false

linter:
  rules:
    always_use_package_imports: true
    directives_ordering: true
    prefer_interpolation_to_compose_strings: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
